// examples/svelte/App.svelte
<script>
  import { onMount } from 'svelte';
  import { injectSpeedInsights } from '@vercel/speed-insights';

  // Alternatively, inject Speed Insights on component mount
  onMount(() => {
    injectSpeedInsights();
  });
</script>

<div id="app">
  <header>
    <h1>✨ Ethereal Presence</h1>
    <p>Svelte app with Vercel Speed Insights</p>
  </header>
  <main>
    <div class="content">
      <p>Speed Insights is now tracking performance metrics.</p>
    </div>
  </main>
</div>

// app/page.tsx
export default function Home() {
  return (
    <main className="container">
      <div className="content">
        <h1>Ethereal Presence</h1>
        <p>Welcome to your Next.js application with Vercel Speed Insights enabled.</p>
        <div className="features">
          <div className="feature-card">
            <h2>Speed Insights</h2>
            <p>Real-time performance monitoring is now active</p>
          </div>
          <div className="feature-card">
            <h2>Client-Side Tracking</h2>
            <p>Performance metrics are collected on the client side</p>
          </div>
          <div className="feature-card">
            <h2>Vercel Analytics</h2>
            <p>View detailed insights in your Vercel dashboard</p>
          </div>
        </div>
      </div>
    </main>
  )
}
